# Generated by Django 5.1 on 2024-09-02 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSE_Students',
            new_name='CSEStudents',
        ),
    ]
