"""
Django settings for PSTU_Enrollment project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pu3q!cs647d*g7vk%wse(*k*r4ji7gudn!e_jc)q&(321taf22'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','d3e9-103-133-254-23.ngrok-free.app']

# For ngrok
CSRF_TRUSTED_ORIGINS = [
    'https://d3e9-103-133-254-23.ngrok-free.app',
    'https://sandbox.sslcommerz.com',
    'https://securepay.sslcommerz.com',
]


# Application definition

INSTALLED_APPS = [
    'clearcache',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'FacultyApp',
    'TeacherApp',
    'StudentApp',
    'ResultApp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PSTU_Enrollment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PSTU_Enrollment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        # For SQLite3
        # =====================================
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        
        # For XAMPP(MariaDB - A fork of MySQL)
        # =====================================
        'ENGINE': 'django.db.backends.mysql',    # MySQL backend for Django
        'NAME': 'pstu_enrollment',               # Database name
        'USER': 'root',                          # Default MySQL username in XAMPP
        'PASSWORD': '',                          # Leave it empty for root, or add your password if you set one
        'HOST': 'localhost',                     # Host (localhost for XAMPP)
        'PORT': '3306',                          # Default MySQL port in XAMPP
        
        # For MySQL(Oracle)
        # =====================================
        # 'ENGINE': 'django.db.backends.mysql',    # MySQL backend for Django
        # 'NAME': 'pstu_enrollment',               # Database name
        # 'USER': 'root',                          # Default MySQL username 
        # 'PASSWORD': 'thisisrootuser',            # Add your password of root user
        # 'HOST': 'localhost',                     # Host (localhost for MySQL Workbench)
        # 'PORT': '3310',                          # Default prot is 3306 but changed to 3310
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT =   os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mehedi.saiyan@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'pvdt baho hwqv mbbw'  # Your generated app password
DEFAULT_FROM_EMAIL = 'mehedi.saiyan@gmail.com'