# Generated by Django 5.1.1 on 2024-09-18 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100, unique=True)),
                ('number_of_semseter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_number', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (9, 'Semester 9'), (10, 'Semester 10'), (11, 'Semester 11'), (12, 'Semester 12'), (13, 'Semester 13'), (14, 'Semester 14'), (15, 'Semester 15')], default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=255, unique=True)),
                ('faculty_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dept_name', 'faculty_name'), name='unique_faculty_dept')],
            },
        ),
        migrations.CreateModel(
            name='FacultyController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'faculty'), name='unique_faculty_admin')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255, unique=True)),
                ('faculty_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.semester')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course_code', 'semester', 'faculty_name'), name='unique_course_code_semester')],
            },
        ),
    ]
