# Generated by Django 5.1 on 2024-09-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('dept_name', 'faculty_name'), name='unique_faculty_dept'),
        ),
    ]
