# Generated by Django 5.1.1 on 2024-09-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
