# Generated by Django 5.1.2 on 2024-10-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0002_course_credit_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=255),
        ),
    ]
