# Generated by Django 5.1 on 2024-09-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
