# Generated by Django 5.1.2 on 2024-10-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0003_alter_course_course_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('enrollment_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cost_per_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('electricity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
