# Generated by Django 5.1 on 2024-09-06 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0003_delete_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20, unique=True)),
                ('faculty_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
            ],
        ),
    ]
