# Generated by Django 5.1.1 on 2024-09-18 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FacultyApp', '0001_initial'),
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('assignment', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('mid_exam', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('final_exam', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.course')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('cgpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.semester')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
    ]
