# Generated by Django 5.1.2 on 2025-06-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FacultyApp', '0001_initial'),
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('assignment', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('mid_exam', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('final_exam', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('letter_grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='F', max_length=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.course')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Regular', 'Regular'), ('F-Removal', 'F-Removal')], default='Regular', max_length=20)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Semester_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('cgpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('curr_sem_credit_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cumulative_credit_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('remark', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Conditional Passed', 'Conditional Passed')], default='Failed', max_length=50)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.semester')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Special_Repeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_period', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
            ],
        ),
    ]
