# Generated by Django 5.1.1 on 2024-10-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultApp', '0003_rename_credit_earned_semester_result_cumulative_credit_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_mark',
            name='grade_point',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='course_mark',
            name='letter_grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='F', max_length=5),
        ),
    ]
