# Generated by Django 5.1.2 on 2024-10-13 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0002_course_credit_hour'),
        ('ResultApp', '0004_course_mark_grade_point_course_mark_letter_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Regular', 'Regular'), ('F-Removal', 'F-Removal'), ('Final', 'Final')], default='Regular', max_length=20)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
            ],
        ),
    ]
