# Generated by Django 5.1.2 on 2024-10-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0003_alter_course_course_title'),
        ('ResultApp', '0005_exam_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_period',
            name='period',
            field=models.CharField(choices=[('Regular', 'Regular'), ('F-Removal', 'F-Removal')], default='Regular', max_length=20),
        ),
        migrations.CreateModel(
            name='Special_Repeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_period', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Disable', max_length=20)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
            ],
        ),
    ]
