# Generated by Django 5.1.1 on 2024-09-18 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FacultyApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('phone_number', models.CharField(max_length=20, null=True, unique=True)),
                ('session', models.CharField(max_length=20, null=True)),
                ('cgpa', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('profile_pic', models.ImageField(upload_to='students_profile_pics/')),
                ('curr_semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.semester')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'student_id', 'faculty'), name='unique_student')],
            },
        ),
    ]
