# Generated by Django 5.1.1 on 2024-09-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
