# Generated by Django 5.1 on 2024-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
