# Generated by Django 5.1.2 on 2024-10-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0002_course_credit_hour'),
        ('StudentApp', '0003_remove_student_cgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid', max_length=50)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.semester')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_id', 'semester', 'payment'), name='unique_payment')],
            },
        ),
    ]
