# Generated by Django 5.1.2 on 2024-10-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Paid', max_length=20),
        ),
    ]
