# Generated by Django 5.1.2 on 2024-10-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0008_student_transaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Conditional Complete', 'Conditional Complete'), ('Incomplete', 'Incomplete')], default='Incomplete', max_length=20),
        ),
    ]
