# Generated by Django 5.1 on 2024-09-06 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0003_delete_department'),
        ('TeacherApp', '0002_teacher_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course_instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.course'),
        ),
    ]
