# Generated by Django 5.1.2 on 2024-10-24 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0003_alter_course_course_title'),
        ('TeacherApp', '0002_teacher_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Course_Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.course')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.teacher')),
            ],
        ),
    ]
