# Generated by Django 5.1 on 2024-09-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0003_delete_department'),
        ('TeacherApp', '0003_teacher_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course_instructor',
        ),
        migrations.CreateModel(
            name='Course_Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.course')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.teacher')),
            ],
        ),
    ]
