# Generated by Django 5.1 on 2024-09-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0004_remove_teacher_course_instructor_course_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_instructor',
            old_name='course_instructor',
            new_name='courseinfo',
        ),
    ]
