# Generated by Django 5.1 on 2024-09-06 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyApp', '0005_alter_department_dept_name'),
        ('TeacherApp', '0005_rename_course_instructor_course_instructor_courseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyApp.department'),
        ),
    ]
